[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
